# Generated by Django 5.1.5 on 2025-02-17 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nameTask', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateCreation', models.DateField()),
            ],
        ),
    ]
