# Generated by Django 5.0.6 on 2025-03-22 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nameTask', models.CharField(max_length=200)),
                ('description', models.TextField(default='none description')),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
