# Generated by Django 5.1.5 on 2025-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
